name: Docker Setup

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to trigger action'
        required: true
        default: 'main'

jobs:
  docker-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4.1.0
        with:
          version: '24.10'
          channel: 'stable'

      - name: Run Docker build
        run: |
          docker build -t my-image .
