- name: Docker Setup Docker
  uses: docker/setup-docker-action@v4.1.0
  with:
    version: v24.0.9  # Optional: specify Docker CE version
    channel: stable   # Optional: specify Docker CE channel (e.g., stable, edge, or test)
    daemon-config: '{"debug": true, "experimental": true}'  # JSON object formatted as a string
    tcp-port: 2375  # Optional: TCP port to expose the Docker API locally
    context: default  # Optional: Docker context name
    set-host: true  # Set DOCKER_HOST environment variable to docker socket path
    rootless: false  # Enable Docker rootless mode (set to true to enable rootless mode)
